name: Git Invaders

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Space Invaders
        uses: VARDHAMANPATEL23/git-invader@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_username: AKKash123
          color: multi
          mode: dark
          ship: rocket

      - name: Publish Space Invaders
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
